FROM ubuntu:14.04

ENV DEBIAN_FRONTEND=noninteractive

ARG ARG_UID
ARG ARG_GID

ADD cfgs/supervisord.conf /etc/supervisord.conf

COPY script1.sh /
RUN /script1.sh

COPY script2.sh /
RUN /script2.sh

COPY script3.sh /
RUN /script3.sh

USER developer

COPY script4.sh /
RUN /script4.sh



# develop part
# java8 for gradle and android studio
COPY jdk-8u471-linux-x64.tar.gz /
RUN \
    tar xzf /jdk-8u471-linux-x64.tar.gz -C /home/developer/

# sdk, ndk
RUN sudo wget http://dl.google.com/android/repository/android-ndk-r12b-linux-x86_64.zip -O /android-ndk-r12b-linux-x86_64.zip && \
    unzip /android-ndk-r12b-linux-x86_64.zip -d /home/developer/ && \
    sudo wget https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz -O /android-sdk_r24.4.1-linux.tgz && \
    tar xzf /android-sdk_r24.4.1-linux.tgz -C /home/developer/

# for sdk manager gui
RUN sudo apt-get update && \
    sudo apt-get install -y openjdk-7-jdk

RUN echo 'export JAVA="/home/developer/jdk1.8.0_471/bin"' >> /home/developer/.bashrc && \
    echo 'export JAVA_HOME="/home/developer/jdk1.8.0_471"' >> /home/developer/.bashrc && \
    echo 'export STUDIO_JDK="/home/developer/jdk1.8.0_471"' >> /home/developer/.bashrc && \
    echo 'export PATH="$JAVA:$PATH"' >> /home/developer/.bashrc && \
    echo 'export ANDROID_HOME="/home/developer/android-sdk-linux"' >> /home/developer/.bashrc && \
    echo 'export ANDROID_TOOLS="/home/developer/android-sdk-linux/tools"' >> /home/developer/.bashrc && \
    true

RUN echo "y" | /home/developer/android-sdk-linux/tools/android update sdk --filter build-tools-24.0.1,extra-android-m2repository,android-15,android-21,android-24,platform-tools --no-ui

RUN sudo wget http://downloads.sourceforge.net/project/opencvlibrary/opencv-android/2.4.10/OpenCV-2.4.10-android-sdk.zip -O /OpenCV-2.4.10-android-sdk.zip && \
    unzip /OpenCV-2.4.10-android-sdk.zip -d /home/developer/

RUN sudo wget https://dl.google.com/dl/android/studio/ide-zips/2.1.2.0/android-studio-ide-143.2915827-linux.zip -O /android-studio-ide-143.2915827-linux.zip && \
    unzip /android-studio-ide-143.2915827-linux.zip -d /home/developer/

# obsolete google-m2repo (required by android studio)
RUN echo "y" | ~/android-sdk-linux/tools/android update sdk -a --filter extra-google-m2repository --no-ui
# update tools
RUN echo "y" | bash -c "/home/developer/android-sdk-linux/tools/android update sdk --filter tools --no-ui; rmdir /home/developer/android-sdk-linux/tools; unzip /home/developer/android-sdk-linux/temp/tools_*-linux.zip -d /tmp/; mv /tmp/tools/ /home/developer/android-sdk-linux/"

RUN /bin/echo -e "if [ -f ~/.bashrc ]; then\n.    ~/.bashrc\nfi" >> /home/developer/.bash_login

RUN sudo usermod -a -G audio developer
# end of develop part
USER root

RUN apt-get install -y supervisor

EXPOSE 22
CMD ["supervisord", "-n", "-c", "/etc/supervisord.conf"]
